### ISSUE TITLE
Change the VirgilAutoConfiguration class to PUBLIC 

### ISSUE THREAD

**Issue by HenghongChen** [indeedeng/virgil-spring-boot-starter#11]
Sometimes, the clients require to NOT initialize the Virgil configurations due to their specific usages (like integration tests).
Making clients enable/disable Virgil's initialization in a flexible way would be really helpful for all users.

Solution:
just a one-line change on the file VirgilAutoConfiguration.java

Please change the Class to Public

**Comment by reedyrm** [comment]
Closing since this issue was resolved with #12
